env:
  global:
  - CC_TEST_REPORTER_ID=1b8ec457c0c30f927f785b4a080eca5164140c5b84716f64809b5ce2f57f3554
language: ruby
sudo: false
cache: bundler
rvm:
- 2.3.7
- 2.4.4
- 2.5.0
- 2.6.2
notifications:
  email: false
  slack:
    secure: e79Y7mFzf+DwnQVg9kniuk9qwtWt1S+7iT8chNMPkugEdsgGt5vKsWvMd0fNmPGsmmHqTaVd4m8Xf4+CpR7nB4oG5pWADrKc4p/syPYWBl/MlC7U3W214oZG5U06hAyJIhpdsC3+ufGHcp3pWUS/SjCUTZgMlp5fNZSh/wzmZe2yWWheFObE2Zj/UAWw0g6WFCmO7ST44Yvy2jhECSIKT9l8ChWr1jXD3h9eDWDJmybySHzO7Tsf/l0gMy92TzqZpjcrPHZsDs+BfVRMucHuO2D72t3WgyJzoVUolYs2nboDUm2IbWzx7Ut/RuvdlG6wv98BJmImzt4ickIZPNzxus56bFHsJQMZ0wSsJR/rAfzwuXqyLd2gQBuSmS352q4w7h4WAVH+i9xhcR5VIazS9tLLGYHEQ7Df/K4fN9+qnOAg+ngDaUU26ChmfsgjXc1fW+9ipzlg7L6OlUOkpypuOGGWKxz0K/gercyJy3DsHS9i1SstgiAEZJ3rJIUUgA9kynuCOEQ8Lv3YodZ+ezqB6HOtk6tZVBpZKDPkvHuapDZikKycvTvyNxD/BugfpRgMub6ac9Ub6aXC2S3xWbD8BHjGWZzRI21LYK6jWBuSu6r5ce2rXWACTWFQbRrNa5iWPXGiTd3sSRoGMZK9yrMdpWJfkhBPHf+6R7RMgiJ499M=
before_install:
- gem update --system
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script: bundle exec rake test spec audit
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
